#%RAML 1.0 Library

# uses:

types:
    ParamsTest:
        type: object
        properties:
            id:
                type: integer
                description: User id
            name:
                type: string
                description: Name
            created_at:
                type: datetime
                description: Creation date
            updated_at:
                type: datetime
                description: Update date
